[[headers]]
for = "/*"

[headers.values]
X-Robots-Tag = "all"

[[headers]]
for = "/feed.xml"

[headers.values]
Content-Type = "application/xml"

[[redirects]]
from = "/rss"
to = "/feed.xml"
status = 301

[[redirects]]
from = "/blog"
to = "/posts"
status = 301

[[redirects]]
from = "/github"
to = "https://github.com/Debbl"
status = 301

[[redirects]]
from = "/gh"
to = "https://github.com/Debbl"
status = 301

[[redirects]]
from = "/slides"
to = "https://slides.aiwan.run"
status = 301


[[redirects]]
from = "/tools"
to = "https://tools.aiwan.run"
status = 301
