packages:
  - 'packages/*'

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - 'es5-ext'
  - 'esbuild'
  - 'sharp'
  - 'simple-git-hooks'
  - 'unrs-resolver'
  - 'workerd'

overrides:
  'eslint-plugin-react-hooks>zod-validation-error': '4.0.2'
